// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7eIY48mpZTH7wsDjhPh9ma5NlBMDj5YI',
    appId: '1:1092849085425:web:b76edf5434eedd76b6b250',
    messagingSenderId: '1092849085425',
    projectId: 'trama-a0971',
    authDomain: 'trama-a0971.firebaseapp.com',
    storageBucket: 'trama-a0971.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9wk0-mdm7JZQkiGrJDdMu9hrPBGbLT8E',
    appId: '1:1092849085425:android:ebe4c5de4805f726b6b250',
    messagingSenderId: '1092849085425',
    projectId: 'trama-a0971',
    storageBucket: 'trama-a0971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXl9GgiKay_MMxjDvT0qNN9R6KqJmhqso',
    appId: '1:1092849085425:ios:70a71bc261ec6065b6b250',
    messagingSenderId: '1092849085425',
    projectId: 'trama-a0971',
    storageBucket: 'trama-a0971.firebasestorage.app',
    iosClientId: '1092849085425-n581j9pl3a4tptcldulq3mu3klq1jt41.apps.googleusercontent.com',
    iosBundleId: 'com.example.tramaApp',
  );
}
